In [1]:
import dgl.nn as dglnn
from dgl import from_networkx
import torch.nn as nn
import torch as th
import torch.nn.functional as F
import dgl.function as fn
import networkx as nx
import pandas as pd
import socket
import struct
import random
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import category_encoders as ce
from sklearn.decomposition import PCA
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

c:\Users\nq100\miniconda3\DLLs\envs\te-g-sage\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
import os
os.chdir(r'C:\Users\nq100\Downloads\TE-G-SAGE-XAI-workspace\TE-G-SAGE-XAI\netflow')
print("CWD:", os.getcwd())   # ← thêm dòng này để debug

import sys
sys.path.append('datasets')
from data_cleaning import clean_nfunsw_nb15

# load this dataset and clean it
data = pd.read_csv('data/NF-Bot-IoT-v3.csv', skiprows=lambda i: i > 0 and i % 70 != 0)

data = clean_nfunsw_nb15(data)

CWD: C:\Users\nq100\Downloads\TE-G-SAGE-XAI-workspace\TE-G-SAGE-XAI\netflow
[clean] Step 1/3: dropped rows missing IP/ports: 0 (from 241911 -> 241911)
[clean] Step 2/3: columns with ±inf and/or missing values detected:
        ['DST_TO_SRC_SECOND_BYTES', 'SRC_TO_DST_SECOND_BYTES']
[clean] Step 3/3: filled 30018 missing numeric values with 0.
[clean] Done. Final shape: (241911, 55)

In [3]:
data.head()

,FLOW_START_MILLISECONDS,FLOW_END_MILLISECONDS,IPV4_SRC_ADDR,L4_SRC_PORT,IPV4_DST_ADDR,L4_DST_PORT,PROTOCOL,L7_PROTO,IN_BYTES,IN_PKTS,...,SRC_TO_DST_IAT_MIN,SRC_TO_DST_IAT_MAX,SRC_TO_DST_IAT_AVG,SRC_TO_DST_IAT_STDDEV,DST_TO_SRC_IAT_MIN,DST_TO_SRC_IAT_MAX,DST_TO_SRC_IAT_AVG,DST_TO_SRC_IAT_STDDEV,Label,Attack
0,1528104433603,1528104433618,192.168.100.3,46560,199.7.83.42,53,17,5.0,56,1,...,0,0,0,0,0,0,0,0,0,Benign
1,1528103789264,1528103789264,192.168.100.149,51032,192.168.100.7,80,6,7.0,52,1,...,0,0,0,0,0,0,0,0,1,DDoS
2,1528103789265,1528103789265,192.168.100.149,51172,192.168.100.7,80,6,7.0,52,1,...,0,0,0,0,0,0,0,0,1,DDoS
3,1528103789266,1528103789266,192.168.100.149,51312,192.168.100.7,80,6,7.0,52,1,...,0,0,0,0,0,0,0,0,1,DDoS
4,1528103789267,1528103789267,192.168.100.149,51452,192.168.100.7,80,6,7.0,52,1,...,0,0,0,0,0,0,0,0,1,DDoS

In [4]:
# anonymize IP addresses by replacing them with random private IPs in the range
# To construct the network graph from the flow data, we mapped the original source IP addresses to randomly assigned
# IP addresses in the range from 172.16.0.1 to 172.31.0.1. The reason for this is the fact that in a lot of the NIDS datasets
# only a small number of IP addresses were used as the source of the attacks. The random mapping avoids
# the potential problem of the source IP addresses providing an unintentional label for attack traffic.
# NOTE: how to modify original randomizer code to temporally consistent flows (i.e., single src to dst should have matching dst to src flow)
#data['IPV4_SRC_ADDR'] = data.IPV4_SRC_ADDR.apply(lambda x: socket.inet_ntoa(struct.pack('>I', random.randint(0xac100001, 0xac1f0001))))

In [5]:
# convert IP addresses and ports to string type then concatenate them to form unique node identifiers
data['IPV4_SRC_ADDR'] = data.IPV4_SRC_ADDR.apply(str)
data['L4_SRC_PORT'] = data.L4_SRC_PORT.apply(str)
data['IPV4_DST_ADDR'] = data.IPV4_DST_ADDR.apply(str)
data['L4_DST_PORT'] = data.L4_DST_PORT.apply(str)

data['IPV4_SRC_ADDR'] = data['IPV4_SRC_ADDR'] + ':' + data['L4_SRC_PORT']
data['IPV4_DST_ADDR'] = data['IPV4_DST_ADDR'] + ':' + data['L4_DST_PORT']

data.drop(columns=['L4_SRC_PORT','L4_DST_PORT'],inplace=True)
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
Index: 241911 entries, 0 to 241910
Data columns (total 53 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   FLOW_START_MILLISECONDS      241911 non-null  int64
 1   FLOW_END_MILLISECONDS        241911 non-null  int64
 2   IPV4_SRC_ADDR                241911 non-null  object
 3   IPV4_DST_ADDR                241911 non-null  object
 4   PROTOCOL                     241911 non-null  int64
 5   L7_PROTO                     241911 non-null  float64
 6   IN_BYTES                     241911 non-null  int64
 7   IN_PKTS                      241911 non-null  int64
 8   OUT_BYTES                    241911 non-null  int64
 9   OUT_PKTS                     241911 non-null  int64
 10  TCP_FLAGS                    241911 non-null  int64
 11  CLIENT_TCP_FLAGS             241911 non-null  int64
 12  SERVER_TCP_FLAGS             241911 non-null  int64
 13  FLOW_DURATION_MILLISECONDS   241911 non-null  int64
 14  DURATION_IN                  241911 non-null  int64
 15  DURATION_OUT                 241911 non-null  int64
 16  MIN_TTL                      241911 non-null  int64
 17  MAX_TTL                      241911 non-null  int64
 18  LONGEST_FLOW_PKT             241911 non-null  int64
 19  SHORTEST_FLOW_PKT            241911 non-null  int64
 20  MIN_IP_PKT_LEN               241911 non-null  int64
 21  MAX_IP_PKT_LEN               241911 non-null  int64
 22  SRC_TO_DST_SECOND_BYTES      241911 non-null  float64
 23  DST_TO_SRC_SECOND_BYTES      241911 non-null  float64
 24  RETRANSMITTED_IN_BYTES       241911 non-null  int64
 25  RETRANSMITTED_IN_PKTS        241911 non-null  int64
 26  RETRANSMITTED_OUT_BYTES      241911 non-null  int64
 27  RETRANSMITTED_OUT_PKTS       241911 non-null  int64
 28  SRC_TO_DST_AVG_THROUGHPUT    241911 non-null  int64
 29  DST_TO_SRC_AVG_THROUGHPUT    241911 non-null  int64
 30  NUM_PKTS_UP_TO_128_BYTES     241911 non-null  int64
 31  NUM_PKTS_128_TO_256_BYTES    241911 non-null  int64
 32  NUM_PKTS_256_TO_512_BYTES    241911 non-null  int64
 33  NUM_PKTS_512_TO_1024_BYTES   241911 non-null  int64
 34  NUM_PKTS_1024_TO_1514_BYTES  241911 non-null  int64
 35  TCP_WIN_MAX_IN               241911 non-null  int64
 36  TCP_WIN_MAX_OUT              241911 non-null  int64
 37  ICMP_TYPE                    241911 non-null  int64
 38  ICMP_IPV4_TYPE               241911 non-null  int64
 39  DNS_QUERY_ID                 241911 non-null  int64
 40  DNS_QUERY_TYPE               241911 non-null  int64
 41  DNS_TTL_ANSWER               241911 non-null  int64
 42  FTP_COMMAND_RET_CODE         241911 non-null  int64
 43  SRC_TO_DST_IAT_MIN           241911 non-null  int64
 44  SRC_TO_DST_IAT_MAX           241911 non-null  int64
 45  SRC_TO_DST_IAT_AVG           241911 non-null  int64
 46  SRC_TO_DST_IAT_STDDEV        241911 non-null  int64
 47  DST_TO_SRC_IAT_MIN           241911 non-null  int64
 48  DST_TO_SRC_IAT_MAX           241911 non-null  int64
 49  DST_TO_SRC_IAT_AVG           241911 non-null  int64
 50  DST_TO_SRC_IAT_STDDEV        241911 non-null  int64
 51  Label                        241911 non-null  int64
 52  Attack                       241911 non-null  object
dtypes: float64(3), int64(47), object(3)
memory usage: 99.7+ MB

,FLOW_START_MILLISECONDS,FLOW_END_MILLISECONDS,IPV4_SRC_ADDR,IPV4_DST_ADDR,PROTOCOL,L7_PROTO,IN_BYTES,IN_PKTS,OUT_BYTES,OUT_PKTS,...,SRC_TO_DST_IAT_MIN,SRC_TO_DST_IAT_MAX,SRC_TO_DST_IAT_AVG,SRC_TO_DST_IAT_STDDEV,DST_TO_SRC_IAT_MIN,DST_TO_SRC_IAT_MAX,DST_TO_SRC_IAT_AVG,DST_TO_SRC_IAT_STDDEV,Label,Attack
0,1528104433603,1528104433618,192.168.100.3:46560,199.7.83.42:53,17,5.0,56,1,1317,1,...,0,0,0,0,0,0,0,0,0,Benign
1,1528103789264,1528103789264,192.168.100.149:51032,192.168.100.7:80,6,7.0,52,1,0,0,...,0,0,0,0,0,0,0,0,1,DDoS
2,1528103789265,1528103789265,192.168.100.149:51172,192.168.100.7:80,6,7.0,52,1,0,0,...,0,0,0,0,0,0,0,0,1,DDoS
3,1528103789266,1528103789266,192.168.100.149:51312,192.168.100.7:80,6,7.0,52,1,0,0,...,0,0,0,0,0,0,0,0,1,DDoS
4,1528103789267,1528103789267,192.168.100.149:51452,192.168.100.7:80,6,7.0,52,1,0,0,...,0,0,0,0,0,0,0,0,1,DDoS

In [6]:
# we don't need the Label column as we are doing multiclass classification
data.drop(columns=['Label'],inplace = True)

In [7]:
data.rename(columns={"Attack": "label"},inplace = True)

## Chronological split of data to 60/30/10

In [8]:
from chronological_split import (
    make_chronological_split_indices,
    save_split_indices, load_split_indices,
    save_split_frames,
)

# df_clean = ...  # output of your data_cleaning.clean_nfunsw_nb15(df_raw)

# 1) Create indices (once)
train_idx, val_idx, test_idx, meta = make_chronological_split_indices(
    data,
    start_col="FLOW_START_MILLISECONDS",  # in ms
    end_col="FLOW_END_MILLISECONDS",
    dur_col="FLOW_DURATION_MILLISECONDS",
    train_ratio=0.60, val_ratio=0.30, test_ratio=0.10, #change to other ratios if needed
)

# 2) Persist indices for future runs
save_split_indices("artifacts/splits", train_idx, val_idx, test_idx, meta)

# (Optional) also dump the materialized split datasets now for reuse
save_split_frames(data, train_idx, val_idx, test_idx, out_dir="artifacts/splits", fmt="parquet")

# 3) In any future run (graph build, feature store, training), load the SAME indices:
train_idx2, val_idx2, test_idx2, meta2 = load_split_indices("artifacts/splits")

# Use them to subset clean dataframe (data) deterministically
df_train = data.loc[train_idx2]
df_val   = data.loc[val_idx2]
df_test  = data.loc[test_idx2]

[split] Chronological 60/30/10 with boundary safety
        TRAIN:   145149  t∈[1526344332972, 1528095906803]
        VAL:      72571  t∈(1528095906803, 1528099941218]
        TEST:     24191  t∈(1528099941218, 1529381825139]
[split] Saved indices → artifacts/splits/split_indices.npz and meta → artifacts/splits/meta.json
[split] Saved materialized splits to artifacts/splits (parquet).

## Label encoding

In [9]:
from label_mapping import fit_label_map, transform_labels, save_label_map, load_label_map, class_weights_from_train

# 1) Fit mapping on TRAIN ONLY
label2id = fit_label_map(df_train["label"], order="alpha")  # or order="freq"
save_label_map("artifacts/label_map.json", label2id)

# 2) Apply mapping to all splits (consistent)
label2id = load_label_map("artifacts/label_map.json")
y_train = transform_labels(df_train["label"], label2id)  # np.int64
y_val   = transform_labels(df_val["label"], label2id, unknown_policy="map_to_last")
y_test  = transform_labels(df_test["label"], label2id, unknown_policy="map_to_last")

# (Optional) sanity check: ensure no -1 slipped in
assert (y_train >= 0).all(), "Train split has unseen/missing labels."

# 3) Class weights for loss
weights = class_weights_from_train(y_train, num_classes=len(label2id))

## Numerical transformation
### Remove highly corelated features
This function visualise correlation between given features.
Also performs log1p, scaler, zero-variance drop, optional Spearman prune on numericals
Applies transformation to test and validation

In [10]:

from feature_numeric import fit_numeric_transform, transform_numeric

# Toggle correlation pruning
APPLY_CORR_PRUNE = True   # set to False to disable pruning and re-run preprocessing
# if you want to check sensitivity of final results to pruning make sure to run train model on best parameters only. and report results.

# 0) Columns to EXCLUDE here because they’re numeric-coded categoricals:
numeric_cats = [
    "PROTOCOL", "L7_PROTO",
    "ICMP_TYPE", "ICMP_IPV4_TYPE",
    # any other *_TYPE / *_ID style columns you want one-hot later
]

# 1) Correlation heatmap (pre-pruning) on TRAIN only
#viz_info = plot_numeric_corr_heatmap(
    #df_train,
    #exclude_numeric_categoricals=numeric_cats,
    #out_dir="artifacts/corr",
    #threshold=0.995,         # same ballpark as your pruning threshold
    #max_features=150,        # avoid unreadable giant plots
    #nonneg_frac=0.995,       # infer nonnegative cols for log1p
    #topk_pairs=100,
    #filename_prefix="spearman_corr_train"
#)
#print("[corr-viz]", viz_info)

# 2) TRAIN: fit numeric pipeline (log1p, scaler, zero-variance drop, optional Spearman prune)
Xnum_train, num_arts = fit_numeric_transform(
    df_train,
    exclude_numeric_categoricals=numeric_cats,
    scaler_type="standard",           # or "robust" if outliers are extreme
    apply_corr_prune=APPLY_CORR_PRUNE,
    corr_threshold=0.995,
    artifacts_dir="artifacts/numeric"
)
print(
    "[numeric] dimensions:",
    "before=", num_arts.dim_before_var,
    "after_variance=", num_arts.dim_after_var,
    "after_correlation=", num_arts.dim_after_corr,
    "Pruning=", APPLY_CORR_PRUNE,
)
print("[numeric] train shape:", Xnum_train.shape)

# 2) VAL/TEST: apply frozen transforms
Xnum_val, _  = transform_numeric(df_val,  artifacts_dir="artifacts/numeric")
Xnum_test, _ = transform_numeric(df_test, artifacts_dir="artifacts/numeric")
print("[numeric] val/test shapes:", Xnum_val.shape, Xnum_test.shape)

[numeric] dimensions: before= 45 after_variance= 45 after_correlation= 31 Pruning= True
[numeric] train shape: (145149, 31)
[numeric] val/test shapes: (72571, 31) (24191, 31)

## Categorical encoding
fits a OneHotEncoder on TRAIN only (sparse CSR, float32),
handles numeric-coded categoricals (e.g., PROTOCOL, L7_PROTO, *_TYPE, *_ID),
Optionally puts IPv4 ports in buckets, collapses rare categories (by min_freq or top_k) - not used here as we droped IPv4 ports after encoding it to unique hosts with IP addresses

persists artifacts (encoder + per-column metadata) for deterministic transforms,
transforms VAL/TEST,
returns CSR matrices ready to stack with numeric transformation.

In [11]:
from categorical_encoding import fit_categorical_transform, transform_categorical

# Choose categorical columns (include your numeric-coded categoricals here!)
cat_cols = [
    "PROTOCOL", "L7_PROTO",
    "ICMP_TYPE", "ICMP_IPV4_TYPE",
    "DNS_QUERY_TYPE", "DNS_QUERY_ID",
    "FTP_COMMAND_RET_CODE",
    # If you want ports as categories (after port bucketing):
    # "L4_SRC_PORT", "L4_DST_PORT", # we dropped ports after concatenating them to IP addresses
    # any other *_TYPE / *_ID style columns you want one-hot
]

# 1) TRAIN — fit encoder (optionally collapse rare cats)
Xcat_train, cat_arts = fit_categorical_transform(
    df_train,
    cat_cols=cat_cols,
    use_port_buckets=False,     # buckets ports into IANA groups to avoid huge dims
    min_freq=50,               # collapse categories with <50 occurrences to "__RARE__" (tune as needed)
    top_k=None,                # or e.g., top_k=20 to keep top-20 per column
    artifacts_dir="artifacts/categorical",
)
print("[categorical] train CSR shape:", Xcat_train.shape)

# 2) VAL/TEST — apply frozen encoder
Xcat_val  = transform_categorical(df_val,  artifacts_dir="artifacts/categorical")
Xcat_test = transform_categorical(df_test, artifacts_dir="artifacts/categorical")
print("[categorical] val/test CSR shapes:", Xcat_val.shape, Xcat_test.shape)

[categorical] train CSR shape: (145149, 21)
[categorical] val/test CSR shapes: (72571, 21) (24191, 21)

## Prepare feature store for mini-batch and other
What: Persist transformed features by split, not in the graph.
Why: Memory safety; fast random access by batch.

a) mini-batch with neighbrour sampling (k-layers)
b) random walk

In [12]:
from feature_store import build_feature_store

# We already have:
# df_train, df_val, df_test       (chronological splits)
# y_train, y_val, y_test          (int labels via label_mapping)
# train_idx, val_idx, test_idx    (global edge indices from persist_splits)

numeric_cats = [
    "PROTOCOL","L7_PROTO","ICMP_TYPE","ICMP_IPV4_TYPE",
    "DNS_QUERY_TYPE","DNS_QUERY_ID","FTP_COMMAND_RET_CODE",
    #"L4_SRC_PORT","L4_DST_PORT",  # if you bucket/one-hot ports - otherwise remove
]

cat_cols = numeric_cats  # plus any extra true categoricals if you have them

shapes = build_feature_store(
    df_train, df_val, df_test,
    y_train, y_val, y_test,
    train_idx, val_idx, test_idx,
    numeric_categoricals=numeric_cats,
    categorical_cols=cat_cols,
    out_dir="feature_store",
    numeric_artifacts_dir="artifacts/numeric",
    categorical_artifacts_dir="artifacts/categorical",
    use_port_buckets=False,
    rare_min_freq=50,
    rare_top_k=None,
    save_timestamps=True,
)
print(shapes)

[feature_store] train: n=145149 d_num=31 d_cat=21
[feature_store] val  : n=72571   d_num=31   d_cat=21
[feature_store] test : n=24191  d_num=31  d_cat=21
{'train': (145149, 31, 21), 'val': (72571, 31, 21), 'test': (24191, 31, 21)}

## Graph construction
What: Build DGL graph without edge features.
Why: Keep memory low; features come from the store per batch (fixed k-hop) or Random walk

No reverse duplication: we add exactly one directed edge per flow from the dataset; reverse flows (if present) appear naturally as their own edges later in time.

Alignment: g.edata[dgl.EID] stores the global edge IDs (original row indices) so your dataloader can fetch edge features from the feature store by ID in every batch.

Minimal memory: edge features live off-graph in the feature store; the graph only carries labels and timestamps.

In [13]:
from graph_build import build_light_graph_for_split

# These point to feature_store splits that were created earlier
split_dirs = {
    "train": "feature_store/train",
    "val":   "feature_store/val",
    "test":  "feature_store/test",
}

# df_train/df_val/df_test are the same dataframes used to build the store
ip2id = None

# build graphs for each split
g_train, ip2id = build_light_graph_for_split(
    df_train, split_dirs["train"],
    ip2id=ip2id, device="cpu",  # keep graphs on CPU; we can move blocks to GPU during training
    save_path="graphs/train.bin"
)

g_val, ip2id = build_light_graph_for_split(
    df_val,   split_dirs["val"],
    ip2id=ip2id, device="cpu",
    save_path="graphs/val.bin"
)

g_test, ip2id = build_light_graph_for_split(
    df_test,  split_dirs["test"],
    ip2id=ip2id, device="cpu",
    save_path="graphs/test.bin"
)

# print node and edge counts
print("Train graph: nodes =", g_train.num_nodes(), "edges =", g_train.num_edges())
print("Val graph:   nodes =", g_val.num_nodes(),   "edges =", g_val.num_edges())
print("Test graph:  nodes =", g_test.num_nodes(),  "edges =", g_test.num_edges())

Train graph: nodes = 117291 edges = 145149
Val graph:   nodes = 156350 edges = 72571
Test graph:  nodes = 167168 edges = 24191

In [14]:
# Create small graphs for hyperparameter testing purposes
# fraction of training edges to use with stratified sampling
import os
from sklearn.model_selection import StratifiedShuffleSplit

FRAC = 0.10

# =======================
# 1) SMALL TRAIN (stratified)
# =======================
# y_train is aligned with df_train = data.loc[train_idx2]
train_pos = np.arange(len(df_train))

sss_tr = StratifiedShuffleSplit(
    n_splits=1,
    train_size=FRAC,
    random_state=42,
)
small_train_pos, _ = next(sss_tr.split(train_pos, y_train))
small_train_pos = np.sort(small_train_pos)

# map positions in df_train back to global indices in `data`
train_idx2_arr = train_idx2.to_numpy() if hasattr(train_idx2, "to_numpy") else np.asarray(train_idx2)
train_sampled = np.sort(train_idx2_arr[small_train_pos])

train_idx_small = pd.Index(train_sampled)
print(
    f"Using {len(train_idx_small)} train edges out of {len(train_idx2)} "
    f"(~{FRAC*100:.1f}%) with stratified sampling"
)

df_train_small = data.loc[train_idx_small]
y_train_small  = y_train[small_train_pos]

# =======================
# 2) SMALL VAL (stratified)
# =======================
val_pos = np.arange(len(df_val))

sss_va = StratifiedShuffleSplit(
    n_splits=1,
    train_size=FRAC,
    random_state=43,
)
small_val_pos, _ = next(sss_va.split(val_pos, y_val))
small_val_pos = np.sort(small_val_pos)

val_idx2_arr = val_idx2.to_numpy() if hasattr(val_idx2, "to_numpy") else np.asarray(val_idx2)
val_sampled = np.sort(val_idx2_arr[small_val_pos])

val_idx_small = pd.Index(val_sampled)
print(
    f"Using {len(val_idx_small)} val edges out of {len(val_idx2)} "
    f"(~{FRAC*100:.1f}%) with stratified sampling"
)

df_val_small = data.loc[val_idx_small]
y_val_small  = y_val[small_val_pos]

# =======================
# 3) Small feature store (train+val small, test full)
# =======================
small_fs_dir = "hyper_tune_small"
os.makedirs(small_fs_dir, exist_ok=True)

numeric_cats = [
    "PROTOCOL","L7_PROTO","ICMP_TYPE","ICMP_IPV4_TYPE",
    "DNS_QUERY_TYPE","DNS_QUERY_ID","FTP_COMMAND_RET_CODE",
]
cat_cols = numeric_cats

shapes_small = build_feature_store(
    df_train_small, df_val_small, df_test,   # <-- small val here
    y_train_small, y_val_small, y_test,
    train_idx_small, val_idx_small, test_idx,
    numeric_categoricals=numeric_cats,
    categorical_cols=cat_cols,
    out_dir=small_fs_dir,
    numeric_artifacts_dir="artifacts/numeric",
    categorical_artifacts_dir="artifacts/categorical",
    use_port_buckets=False,
    rare_min_freq=50,
    rare_top_k=None,
    save_timestamps=True,
)
print("[small fs] shapes:", shapes_small)

# =======================
# 4) Small graphs (train+val small, test full)
# =======================
os.makedirs("graphs_small", exist_ok=True)

g_train_small, ip2id_small = build_light_graph_for_split(
    df_train_small, os.path.join(small_fs_dir, "train"),
    ip2id=None, device="cpu",
    save_path="graphs_small/train.bin",
)
g_val_small, ip2id_small = build_light_graph_for_split(
    df_val_small, os.path.join(small_fs_dir, "val"),   # <-- small val here
    ip2id=ip2id_small, device="cpu",
    save_path="graphs_small/val.bin",
)

print("Small train graph: nodes =", g_train_small.num_nodes(), "edges =", g_train_small.num_edges())
print("Small val graph:   nodes =", g_val_small.num_nodes(),   "edges =", g_val_small.num_edges())

Using 14514 train edges out of 145149 (~10.0%) with stratified sampling
Using 7257 val edges out of 72571 (~10.0%) with stratified sampling
[feature_store] train: n=14514 d_num=31 d_cat=15
[feature_store] val  : n=7257   d_num=31   d_cat=15
[feature_store] test : n=24191  d_num=31  d_cat=15
[small fs] shapes: {'train': (14514, 31, 15), 'val': (7257, 31, 15), 'test': (24191, 31, 15)}
Small train graph: nodes = 14808 edges = 14514
Small val graph:   nodes = 21639 edges = 7257

Sanity check

In [15]:
#Sanity check
import numpy as np, os
ytr = np.load("feature_store/train/y.npy"); yva = np.load("feature_store/val/y.npy")
print("train uniques:", np.unique(ytr), "size:", ytr.size)
print("val uniques  :", np.unique(yva), "size:", yva.size)
assert ytr.min() >= 0

train uniques: [0 1 2 3] size: 145149
val uniques  : [0 1] size: 72571

In [16]:
# graph sanity check
# one sample e_feat
import dgl, numpy as np

g = dgl.load_graphs("graphs/train.bin")[0][0]
sample_eids = g.edata[dgl.EID].cpu().numpy()
store_eids = np.load("feature_store/train/edge_indices.npy")
# start_idx_graph = np.where(sample_eids == 249625)[0][0]
# print("Sample EIDs from graph:", sample_eids[start_idx_graph:start_idx_graph+10])
print("Min EID:", store_eids.min(), "Max EID:", store_eids.max())
print("First 20 EIDs:", store_eids[:20])
print("Is 249625 in store_eids?", 249625 in store_eids)

print("graph_eids.shape:", sample_eids.shape, "min:", sample_eids.min(), "max:", sample_eids.max())
present_in_graph = np.any(sample_eids == 249625)
print("249625 in graph?", present_in_graph)

sample = g.edata[dgl.EID][:8].cpu().numpy()
from feature_store import fetch_edge_features
e = fetch_edge_features(sample, "feature_store/train")
print("edge feature dim:", e.shape[1])  # should equal edge_in (inferred)

Min EID: 1071 Max EID: 241881
First 20 EIDs: [239596 239597 239598 239599 239600 239601 239602 239603 239604 239605
 239606 239607 239608 239609 239610 239611 239612 239613 239614 239615]
Is 249625 in store_eids? False
graph_eids.shape: (145149,) min: 1071 max: 241881
249625 in graph? False
edge feature dim: 52

In [17]:
import os, numpy as np, dgl
# prove the split is “wired through” correctly
def assert_graph_equals_store(g, split_dir, name):
    s = np.load(os.path.join(split_dir, "edge_indices.npy")).astype(np.int64)
    ge = g.edata[dgl.EID].cpu().numpy().astype(np.int64)
    print(f"[{name}] graph={ge.size} store={s.size}")
    assert s.shape == ge.shape and np.array_equal(s, ge), f"{name}: graph EIDs != store edge_indices"

assert_graph_equals_store(g_train, "feature_store/train", "train")
assert_graph_equals_store(g_val,   "feature_store/val",   "val")
print("✅ graph == store for both splits")

[train] graph=145149 store=145149
[val] graph=72571 store=72571
✅ graph == store for both splits

In [18]:
# Check if we have node features and their shape (we dont so it should be None)
import dgl, torch
g = dgl.load_graphs("graphs/train.bin")[0][0]
print("has node feats:", "x" in g.ndata, "shape:" , (None if "x" not in g.ndata else tuple(g.ndata["x"].shape)))

has node feats: False shape: None

### Training

In [19]:
# training script for edge classification. Can be called from CLI or imported as a module
import copy, os, json, shutil
from types import SimpleNamespace

import torch
from train_edgecls_dbg import run_training

base_args = SimpleNamespace(
    feature_store="hyper_tune_small",   # use small FS for hyperparam tuning
    graphs_dir="graphs_small",          # use small graphs for hyperparam tuning
    split_train="train",
    split_val="val",
    hidden=128,         # 64, 128, 256
    layers=2,
    aggregator="mean",  # mean, pool, lstm, gcn
    edge_in=0,               # infer from sample
    edge_mlp_hidden=128,
    dropout=0.3,
    fanouts="25,15",    # 15,10 or 25,15 or 35,25
    batch_size=2048,    # 256, 512, 1024, 2048
    epochs=25,
    lr=3e-4,
    weight_decay=1e-4,
    device="cuda" if torch.cuda.is_available() else "cpu",
    num_workers=0,
    seed=42,
    debug=False,
)
# hyperparameters
hiddens = [64, 128]
aggregators = ["mean"]
fanouts_grid = [(15,10), (25,15)]
dropouts = [0.2, 0.3, 0.4]
batch_sizes = [256, 512, 1024]

os.makedirs("artifacts/grid_models", exist_ok=True)
os.makedirs("artifacts/grid_logs", exist_ok=True)
results = []

for hidden in hiddens:
    for agg in aggregators:
        for bs in batch_sizes:
            for fan in fanouts_grid:
                for dr in dropouts:
                    args = copy.deepcopy(base_args)
                    args.hidden = hidden
                    args.aggregator = agg
                    args.dropout = dr
                    args.fanouts = f"{fan[0]},{fan[1]}"   # run_training expects string here
                    args.batch_size = bs
                    run_name = f"hid{hidden}_agg{agg}_fan{fan[0]}-{fan[1]}_drop{int(dr*100):02d}_bs{bs}"
                    print(f"=== RUN: {run_name} ===")
                    try:
                        res = run_training(args)   # returns dict with best_val_acc, edge_in, fanouts, history
                    except Exception as e:
                        print(f"[ERROR] run failed for {run_name}: {e}")
                        results.append({"run": run_name, "error": str(e)})
                        continue

                    best_acc = float(res.get("best_val_acc", -1.0))
                    # copy saved checkpoint (if run_training saved one) to unique path
                    src = "artifacts/best_edge_sage.pt"
                    dst = os.path.join("artifacts/grid_models", f"best_{run_name}.pt")
                    if os.path.exists(src):
                        shutil.copy(src, dst)
                    else:
                        dst = None
                    
                    # save per-epoch history for this run (acc, time etc.)
                    history = res.get("history", None)
                    if history is not None:
                        hist_path = os.path.join("artifacts/grid_logs", f"{run_name}_history.json")
                        with open(hist_path, "w", encoding="utf-8") as f:
                            json.dump(history, f, indent=2)
                    else:
                        hist_path = None

                    results.append({
                        "run": run_name,
                        "config": {
                            "hidden": hidden,
                            "aggregator": agg,
                            "fanouts": f"{fan[0]},{fan[1]}",
                            "dropout": dr,
                            "batch_size": bs,
                            "epochs": args.epochs,
                        },
                        "best_val_acc": best_acc,
                        "model_path": dst,
                        "train_return": res,
                        "history_path": hist_path,  # <--- pointer to per-epoch metrics if exists
                    })

                    # optional: remove the generic artifact so next run doesn't accidentally reuse it
                    if os.path.exists(src):
                        os.remove(src)

# persist results
with open("artifacts/grid_search_results.json", "w", encoding="utf-8") as f:
    json.dump(results, f, indent=2)

# print best trial
valid_results = [r for r in results if r.get("model_path")]
best = max(valid_results, key=lambda r: r["best_val_acc"]) if valid_results else None
print("BEST:", best)
# persist canonical model + params for other notebooks to load
os.makedirs("artifacts", exist_ok=True)
best_model_dst = "artifacts/best_edge_sage.pt"
best_params_path = "artifacts/best_params.json"

if best and best.get("model_path"):
    # copy the per-run checkpoint to the canonical filename expected by downstream code
    shutil.copy(best["model_path"], best_model_dst)

    # save minimal params so other notebooks can re-create the model/config
    params = {
        "run": best.get("run"),
        "config": best.get("config"),
        "best_val_acc": best.get("best_val_acc"),
        "model_path": best_model_dst,
    }
    with open(best_params_path, "w", encoding="utf-8") as f:
        json.dump(params, f, indent=2)

    print(f"Saved best model -> {best_model_dst} and params -> {best_params_path}")
else:
    if os.path.exists(best_model_dst):
        print(f"No successful new run — keeping existing {best_model_dst}")
    else:
        print("Warning: no best model available and artifacts/best_edge_sage.pt is missing")

=== RUN: hid64_aggmean_fan15-10_drop20_bs256 ===
2026-09-09 12:20:08,544 INFO [model] SAGE[0]: in=None out=None hidden=64 edge_in=46 in_node=0

c:\Users\nq100\miniconda3\DLLs\envs\te-g-sage\lib\site-packages\dgl\dataloading\dataloader.py:1149: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
  dgl_warning(

2026-09-09 12:20:11,047 INFO [timing] epoch: total_loss=16862.3860 total_time=1.0128s (avg batch 0.018s)
2026-09-09 12:20:11,405 INFO [timing] epoch: total_loss=15014.4944 total_time=0.3559s (avg batch 0.012s)
2026-09-09 12:20:11,407 INFO [epoch 01] train loss 1.1618 train acc 0.5126 | val loss 2.0690 val acc 0.0227
2026-09-09 12:20:12,423 INFO [timing] epoch: total_loss=13201.1016 total_time=1.0091s (avg batch 0.018s)
2026-09-09 12:20:12,772 INFO [timing] epoch: total_loss=23279.9560 total_time=0.3480s (avg batch 0.012s)
2026-09-09 12:20:12,773 INFO [epoch 02] train loss 0.9095 train acc 0.5691 | val loss 3.2079 val acc 0.0054
2026-09-09 12:20:13,753 INFO [timing] epoch: total_loss=12053.3836 total_time=0.9794s (avg batch 0.017s)
2026-09-09 12:20:14,100 INFO [timing] epoch: total_loss=25286.4979 total_time=0.3450s (avg batch 0.012s)
2026-09-09 12:20:14,101 INFO [epoch 03] train loss 0.8305 train acc 0.5594 | val loss 3.4844 val acc 0.0227
2026-09-09 12:20:15,059 INFO [timing] epoch: total_loss=11537.1416 total_time=0.9578s (avg batch 0.017s)
2026-09-09 12:20:15,378 INFO [timing] epoch: total_loss=31539.0713 total_time=0.3183s (avg batch 0.011s)
2026-09-09 12:20:15,379 INFO [epoch 04] train loss 0.7949 train acc 0.5400 | val loss 4.3460 val acc 0.0047
2026-09-09 12:20:16,300 INFO [timing] epoch: total_loss=11368.9145 total_time=0.9198s (avg batch 0.016s)
2026-09-09 12:20:16,628 INFO [timing] epoch: total_loss=35411.4547 total_time=0.3269s (avg batch 0.011s)
2026-09-09 12:20:16,629 INFO [epoch 05] train loss 0.7833 train acc 0.5802 | val loss 4.8796 val acc 0.0047
2026-09-09 12:20:17,548 INFO [timing] epoch: total_loss=11173.0936 total_time=0.9181s (avg batch 0.016s)
2026-09-09 12:20:17,871 INFO [timing] epoch: total_loss=36189.1160 total_time=0.3214s (avg batch 0.011s)
2026-09-09 12:20:17,872 INFO [epoch 06] train loss 0.7698 train acc 0.5531 | val loss 4.9868 val acc 0.0048
2026-09-09 12:20:18,790 INFO [timing] epoch: total_loss=11064.3058 total_time=0.9168s (avg batch 0.016s)
2026-09-09 12:20:19,109 INFO [timing] epoch: total_loss=38425.2911 total_time=0.3178s (avg batch 0.011s)
2026-09-09 12:20:19,110 INFO [epoch 07] train loss 0.7623 train acc 0.5508 | val loss 5.2949 val acc 0.0047
2026-09-09 12:20:20,030 INFO [timing] epoch: total_loss=11153.0649 total_time=0.9188s (avg batch 0.016s)
2026-09-09 12:20:20,356 INFO [timing] epoch: total_loss=39855.4888 total_time=0.3254s (avg batch 0.011s)
2026-09-09 12:20:20,358 INFO [epoch 08] train loss 0.7684 train acc 0.5628 | val loss 5.4920 val acc 0.0047
2026-09-09 12:20:21,290 INFO [timing] epoch: total_loss=10980.6681 total_time=0.9306s (avg batch 0.016s)
2026-09-09 12:20:21,614 INFO [timing] epoch: total_loss=40501.2666 total_time=0.3239s (avg batch 0.011s)
2026-09-09 12:20:21,616 INFO [epoch 09] train loss 0.7566 train acc 0.5695 | val loss 5.5810 val acc 0.0047
2026-09-09 12:20:22,544 INFO [timing] epoch: total_loss=10982.1605 total_time=0.9284s (avg batch 0.016s)
2026-09-09 12:20:22,866 INFO [timing] epoch: total_loss=41800.6861 total_time=0.3206s (avg batch 0.011s)
2026-09-09 12:20:22,867 INFO [epoch 10] train loss 0.7567 train acc 0.5692 | val loss 5.7601 val acc 0.0045
2026-09-09 12:20:23,795 INFO [timing] epoch: total_loss=10836.9196 total_time=0.9272s (avg batch 0.016s)
2026-09-09 12:20:24,124 INFO [timing] epoch: total_loss=43203.7808 total_time=0.3273s (avg batch 0.011s)
2026-09-09 12:20:24,125 INFO [epoch 11] train loss 0.7467 train acc 0.5646 | val loss 5.9534 val acc 0.0047
2026-09-09 12:20:25,058 INFO [timing] epoch: total_loss=10821.6456 total_time=0.9330s (avg batch 0.016s)
2026-09-09 12:20:25,399 INFO [timing] epoch: total_loss=43900.5077 total_time=0.3386s (avg batch 0.012s)
2026-09-09 12:20:25,400 INFO [epoch 12] train loss 0.7456 train acc 0.5601 | val loss 6.0494 val acc 0.0047
2026-09-09 12:20:26,331 INFO [timing] epoch: total_loss=10839.5879 total_time=0.9302s (avg batch 0.016s)
2026-09-09 12:20:26,650 INFO [timing] epoch: total_loss=44591.8932 total_time=0.3178s (avg batch 0.011s)
2026-09-09 12:20:26,651 INFO [epoch 13] train loss 0.7468 train acc 0.5667 | val loss 6.1447 val acc 0.0043
2026-09-09 12:20:27,582 INFO [timing] epoch: total_loss=10799.9530 total_time=0.9303s (avg batch 0.016s)
2026-09-09 12:20:27,906 INFO [timing] epoch: total_loss=47532.4283 total_time=0.3233s (avg batch 0.011s)
2026-09-09 12:20:27,907 INFO [epoch 14] train loss 0.7441 train acc 0.5701 | val loss 6.5499 val acc 0.0015
2026-09-09 12:20:28,832 INFO [timing] epoch: total_loss=10861.4216 total_time=0.9236s (avg batch 0.016s)
2026-09-09 12:20:29,153 INFO [timing] epoch: total_loss=46307.2534 total_time=0.3207s (avg batch 0.011s)
2026-09-09 12:20:29,154 INFO [epoch 15] train loss 0.7483 train acc 0.5636 | val loss 6.3810 val acc 0.0043
2026-09-09 12:20:30,086 INFO [timing] epoch: total_loss=10815.8043 total_time=0.9303s (avg batch 0.016s)
2026-09-09 12:20:30,420 INFO [timing] epoch: total_loss=46603.9294 total_time=0.3322s (avg batch 0.011s)
2026-09-09 12:20:30,421 INFO [epoch 16] train loss 0.7452 train acc 0.5473 | val loss 6.4219 val acc 0.0043
2026-09-09 12:20:31,491 INFO [timing] epoch: total_loss=10761.7464 total_time=1.0693s (avg batch 0.019s)
2026-09-09 12:20:31,878 INFO [timing] epoch: total_loss=47798.0449 total_time=0.3860s (avg batch 0.013s)
2026-09-09 12:20:31,879 INFO [epoch 17] train loss 0.7415 train acc 0.5730 | val loss 6.5865 val acc 0.0043
2026-09-09 12:20:32,934 INFO [timing] epoch: total_loss=10720.2490 total_time=1.0544s (avg batch 0.018s)
2026-09-09 12:20:33,342 INFO [timing] epoch: total_loss=48784.5476 total_time=0.4055s (avg batch 0.014s)
2026-09-09 12:20:33,344 INFO [epoch 18] train loss 0.7386 train acc 0.5617 | val loss 6.7224 val acc 0.0036
2026-09-09 12:20:34,599 INFO [timing] epoch: total_loss=10697.7982 total_time=1.2546s (avg batch 0.022s)
2026-09-09 12:20:35,033 INFO [timing] epoch: total_loss=48966.9735 total_time=0.4323s (avg batch 0.015s)
2026-09-09 12:20:35,034 INFO [epoch 19] train loss 0.7371 train acc 0.5719 | val loss 6.7476 val acc 0.0015
2026-09-09 12:20:36,287 INFO [timing] epoch: total_loss=10642.0517 total_time=1.2515s (avg batch 0.022s)
2026-09-09 12:20:36,706 INFO [timing] epoch: total_loss=49881.4209 total_time=0.4179s (avg batch 0.014s)
2026-09-09 12:20:36,707 INFO [epoch 20] train loss 0.7332 train acc 0.5590 | val loss 6.8736 val acc 0.0033
2026-09-09 12:20:37,971 INFO [timing] epoch: total_loss=10614.2272 total_time=1.2625s (avg batch 0.022s)
2026-09-09 12:20:38,387 INFO [timing] epoch: total_loss=50432.9145 total_time=0.4145s (avg batch 0.014s)
2026-09-09 12:20:38,389 INFO [epoch 21] train loss 0.7313 train acc 0.5673 | val loss 6.9496 val acc 0.0015
2026-09-09 12:20:39,622 INFO [timing] epoch: total_loss=10545.2858 total_time=1.2319s (avg batch 0.022s)
2026-09-09 12:20:40,020 INFO [timing] epoch: total_loss=50096.5852 total_time=0.3973s (avg batch 0.014s)
2026-09-09 12:20:40,021 INFO [epoch 22] train loss 0.7266 train acc 0.5779 | val loss 6.9032 val acc 0.0037
2026-09-09 12:20:41,214 INFO [timing] epoch: total_loss=10600.8133 total_time=1.1924s (avg batch 0.021s)
2026-09-09 12:20:41,621 INFO [timing] epoch: total_loss=50515.9008 total_time=0.4061s (avg batch 0.014s)
2026-09-09 12:20:41,623 INFO [epoch 23] train loss 0.7304 train acc 0.5552 | val loss 6.9610 val acc 0.0019
2026-09-09 12:20:42,765 INFO [timing] epoch: total_loss=10519.2592 total_time=1.1411s (avg batch 0.020s)
2026-09-09 12:20:43,171 INFO [timing] epoch: total_loss=52058.8684 total_time=0.4037s (avg batch 0.014s)
2026-09-09 12:20:43,173 INFO [epoch 24] train loss 0.7248 train acc 0.5711 | val loss 7.1736 val acc 0.0015
2026-09-09 12:20:44,333 INFO [timing] epoch: total_loss=10466.1585 total_time=1.1603s (avg batch 0.020s)
2026-09-09 12:20:44,750 INFO [timing] epoch: total_loss=51810.0862 total_time=0.4137s (avg batch 0.014s)
2026-09-09 12:20:44,751 INFO [epoch 25] train loss 0.7211 train acc 0.5724 | val loss 7.1393 val acc 0.0015
2026-09-09 12:20:44,752 INFO Best val acc: 0.0227
=== RUN: hid64_aggmean_fan15-10_drop30_bs256 ===
2026-09-09 12:20:44,782 INFO [model] SAGE[0]: in=None out=None hidden=64 edge_in=46 in_node=0
2026-09-09 12:20:45,969 INFO [timing] epoch: total_loss=17051.0750 total_time=1.1785s (avg batch 0.021s)
2026-09-09 12:20:46,372 INFO [timing] epoch: total_loss=14607.9473 total_time=0.4019s (avg batch 0.014s)
2026-09-09 12:20:46,373 INFO [epoch 01] train loss 1.1748 train acc 0.4609 | val loss 2.0129 val acc 0.0227
2026-09-09 12:20:47,546 INFO [timing] epoch: total_loss=13313.4575 total_time=1.1690s (avg batch 0.021s)
2026-09-09 12:20:47,951 INFO [timing] epoch: total_loss=23471.9435 total_time=0.4037s (avg batch 0.014s)
2026-09-09 12:20:47,952 INFO [epoch 02] train loss 0.9173 train acc 0.5686 | val loss 3.2344 val acc 0.0227
2026-09-09 12:20:49,101 INFO [timing] epoch: total_loss=12019.9869 total_time=1.1475s (avg batch 0.020s)
2026-09-09 12:20:49,510 INFO [timing] epoch: total_loss=27947.3985 total_time=0.4075s (avg batch 0.014s)
2026-09-09 12:20:49,511 INFO [epoch 03] train loss 0.8282 train acc 0.5526 | val loss 3.8511 val acc 0.0047
2026-09-09 12:20:50,698 INFO [timing] epoch: total_loss=11673.2731 total_time=1.1862s (avg batch 0.021s)
2026-09-09 12:20:51,120 INFO [timing] epoch: total_loss=31051.3692 total_time=0.4211s (avg batch 0.015s)
2026-09-09 12:20:51,121 INFO [epoch 04] train loss 0.8043 train acc 0.5577 | val loss 4.2788 val acc 0.0050
2026-09-09 12:20:52,292 INFO [timing] epoch: total_loss=11290.8935 total_time=1.1701s (avg batch 0.021s)
2026-09-09 12:20:52,695 INFO [timing] epoch: total_loss=32775.2281 total_time=0.4020s (avg batch 0.014s)
2026-09-09 12:20:52,697 INFO [epoch 05] train loss 0.7779 train acc 0.5760 | val loss 4.5164 val acc 0.0052
2026-09-09 12:20:53,825 INFO [timing] epoch: total_loss=11396.6346 total_time=1.1271s (avg batch 0.020s)
2026-09-09 12:20:54,293 INFO [timing] epoch: total_loss=34765.6486 total_time=0.4650s (avg batch 0.016s)
2026-09-09 12:20:54,295 INFO [epoch 06] train loss 0.7852 train acc 0.5522 | val loss 4.7906 val acc 0.0047
2026-09-09 12:20:55,575 INFO [timing] epoch: total_loss=11247.6662 total_time=1.2788s (avg batch 0.022s)
2026-09-09 12:20:56,019 INFO [timing] epoch: total_loss=36736.9198 total_time=0.4427s (avg batch 0.015s)
2026-09-09 12:20:56,021 INFO [epoch 07] train loss 0.7750 train acc 0.5689 | val loss 5.0623 val acc 0.0047
2026-09-09 12:20:57,259 INFO [timing] epoch: total_loss=11107.5469 total_time=1.2363s (avg batch 0.022s)
2026-09-09 12:20:57,753 INFO [timing] epoch: total_loss=39241.3574 total_time=0.4925s (avg batch 0.017s)
2026-09-09 12:20:57,755 INFO [epoch 08] train loss 0.7653 train acc 0.5554 | val loss 5.4074 val acc 0.0043
2026-09-09 12:20:59,012 INFO [timing] epoch: total_loss=11242.9778 total_time=1.2554s (avg batch 0.022s)
2026-09-09 12:20:59,418 INFO [timing] epoch: total_loss=38116.5151 total_time=0.4051s (avg batch 0.014s)
2026-09-09 12:20:59,419 INFO [epoch 09] train loss 0.7746 train acc 0.5444 | val loss 5.2524 val acc 0.0047
2026-09-09 12:21:00,607 INFO [timing] epoch: total_loss=11007.0098 total_time=1.1868s (avg batch 0.021s)
2026-09-09 12:21:01,063 INFO [timing] epoch: total_loss=38833.3704 total_time=0.4547s (avg batch 0.016s)
2026-09-09 12:21:01,064 INFO [epoch 10] train loss 0.7584 train acc 0.5581 | val loss 5.3512 val acc 0.0047
2026-09-09 12:21:02,307 INFO [timing] epoch: total_loss=10996.6810 total_time=1.2419s (avg batch 0.022s)
2026-09-09 12:21:02,690 INFO [timing] epoch: total_loss=38687.6587 total_time=0.3810s (avg batch 0.013s)
2026-09-09 12:21:02,692 INFO [epoch 11] train loss 0.7577 train acc 0.5760 | val loss 5.3311 val acc 0.0047
2026-09-09 12:21:03,781 INFO [timing] epoch: total_loss=10833.4321 total_time=1.0887s (avg batch 0.019s)
2026-09-09 12:21:04,162 INFO [timing] epoch: total_loss=41042.3616 total_time=0.3797s (avg batch 0.013s)
2026-09-09 12:21:04,164 INFO [epoch 12] train loss 0.7464 train acc 0.5504 | val loss 5.6556 val acc 0.0047
2026-09-09 12:21:05,295 INFO [timing] epoch: total_loss=10973.9257 total_time=1.1298s (avg batch 0.020s)
2026-09-09 12:21:05,696 INFO [timing] epoch: total_loss=40524.8625 total_time=0.3983s (avg batch 0.014s)
2026-09-09 12:21:05,697 INFO [epoch 13] train loss 0.7561 train acc 0.5648 | val loss 5.5842 val acc 0.0044
2026-09-09 12:21:06,842 INFO [timing] epoch: total_loss=10744.6951 total_time=1.1437s (avg batch 0.020s)
2026-09-09 12:21:07,234 INFO [timing] epoch: total_loss=43039.9073 total_time=0.3914s (avg batch 0.013s)
2026-09-09 12:21:07,236 INFO [epoch 14] train loss 0.7403 train acc 0.5629 | val loss 5.9308 val acc 0.0021
2026-09-09 12:21:08,350 INFO [timing] epoch: total_loss=10920.2019 total_time=1.1128s (avg batch 0.020s)
2026-09-09 12:21:08,742 INFO [timing] epoch: total_loss=41396.0164 total_time=0.3905s (avg batch 0.013s)
2026-09-09 12:21:08,743 INFO [epoch 15] train loss 0.7524 train acc 0.5832 | val loss 5.7043 val acc 0.0043
2026-09-09 12:21:09,859 INFO [timing] epoch: total_loss=10814.4618 total_time=1.1153s (avg batch 0.020s)
2026-09-09 12:21:10,257 INFO [timing] epoch: total_loss=41692.7035 total_time=0.3959s (avg batch 0.014s)
2026-09-09 12:21:10,260 INFO [epoch 16] train loss 0.7451 train acc 0.5712 | val loss 5.7452 val acc 0.0043
2026-09-09 12:21:11,378 INFO [timing] epoch: total_loss=10669.2170 total_time=1.1183s (avg batch 0.020s)
2026-09-09 12:21:11,758 INFO [timing] epoch: total_loss=43099.0759 total_time=0.3792s (avg batch 0.013s)
2026-09-09 12:21:11,759 INFO [epoch 17] train loss 0.7351 train acc 0.5673 | val loss 5.9390 val acc 0.0043
2026-09-09 12:21:12,880 INFO [timing] epoch: total_loss=10697.5516 total_time=1.1197s (avg batch 0.020s)
2026-09-09 12:21:13,263 INFO [timing] epoch: total_loss=46407.8783 total_time=0.3810s (avg batch 0.013s)
2026-09-09 12:21:13,264 INFO [epoch 18] train loss 0.7371 train acc 0.5654 | val loss 6.3949 val acc 0.0021
2026-09-09 12:21:14,358 INFO [timing] epoch: total_loss=10777.5327 total_time=1.0932s (avg batch 0.019s)
2026-09-09 12:21:14,738 INFO [timing] epoch: total_loss=43956.7082 total_time=0.3777s (avg batch 0.013s)
2026-09-09 12:21:14,740 INFO [epoch 19] train loss 0.7426 train acc 0.5541 | val loss 6.0571 val acc 0.0019
2026-09-09 12:21:15,829 INFO [timing] epoch: total_loss=10682.2862 total_time=1.0876s (avg batch 0.019s)
2026-09-09 12:21:16,205 INFO [timing] epoch: total_loss=46306.1703 total_time=0.3750s (avg batch 0.013s)
2026-09-09 12:21:16,207 INFO [epoch 20] train loss 0.7360 train acc 0.5552 | val loss 6.3809 val acc 0.0019
2026-09-09 12:21:17,311 INFO [timing] epoch: total_loss=10517.4236 total_time=1.1033s (avg batch 0.019s)
2026-09-09 12:21:17,704 INFO [timing] epoch: total_loss=47651.8468 total_time=0.3916s (avg batch 0.014s)
2026-09-09 12:21:17,705 INFO [epoch 21] train loss 0.7246 train acc 0.5659 | val loss 6.5663 val acc 0.0010
2026-09-09 12:21:18,815 INFO [timing] epoch: total_loss=10632.4266 total_time=1.1085s (avg batch 0.019s)
2026-09-09 12:21:19,223 INFO [timing] epoch: total_loss=49013.5251 total_time=0.4046s (avg batch 0.014s)
2026-09-09 12:21:19,224 INFO [epoch 22] train loss 0.7326 train acc 0.5437 | val loss 6.7540 val acc 0.0019
2026-09-09 12:21:20,340 INFO [timing] epoch: total_loss=10772.7296 total_time=1.1149s (avg batch 0.020s)
2026-09-09 12:21:20,722 INFO [timing] epoch: total_loss=47032.3518 total_time=0.3806s (avg batch 0.013s)
2026-09-09 12:21:20,724 INFO [epoch 23] train loss 0.7422 train acc 0.5708 | val loss 6.4810 val acc 0.0019
2026-09-09 12:21:21,832 INFO [timing] epoch: total_loss=10650.0721 total_time=1.1073s (avg batch 0.019s)
2026-09-09 12:21:22,211 INFO [timing] epoch: total_loss=48870.3425 total_time=0.3766s (avg batch 0.013s)
2026-09-09 12:21:22,213 INFO [epoch 24] train loss 0.7338 train acc 0.5743 | val loss 6.7342 val acc 0.0019
2026-09-09 12:21:23,323 INFO [timing] epoch: total_loss=10494.5245 total_time=1.1091s (avg batch 0.019s)
2026-09-09 12:21:23,714 INFO [timing] epoch: total_loss=47982.5785 total_time=0.3899s (avg batch 0.013s)
2026-09-09 12:21:23,715 INFO [epoch 25] train loss 0.7231 train acc 0.5674 | val loss 6.6119 val acc 0.0019
2026-09-09 12:21:23,716 INFO Best val acc: 0.0227
=== RUN: hid64_aggmean_fan15-10_drop40_bs256 ===
2026-09-09 12:21:23,745 INFO [model] SAGE[0]: in=None out=None hidden=64 edge_in=46 in_node=0
2026-09-09 12:21:24,913 INFO [timing] epoch: total_loss=16983.1956 total_time=1.1611s (avg batch 0.020s)
2026-09-09 12:21:25,298 INFO [timing] epoch: total_loss=16949.7778 total_time=0.3832s (avg batch 0.013s)
2026-09-09 12:21:25,299 INFO [epoch 01] train loss 1.1701 train acc 0.5318 | val loss 2.3356 val acc 0.0227
2026-09-09 12:21:26,437 INFO [timing] epoch: total_loss=13364.5164 total_time=1.1323s (avg batch 0.020s)
2026-09-09 12:21:26,812 INFO [timing] epoch: total_loss=21728.7661 total_time=0.3747s (avg batch 0.013s)
2026-09-09 12:21:26,814 INFO [epoch 02] train loss 0.9208 train acc 0.5646 | val loss 2.9942 val acc 0.0227
2026-09-09 12:21:27,928 INFO [timing] epoch: total_loss=12220.1746 total_time=1.1142s (avg batch 0.020s)
2026-09-09 12:21:28,309 INFO [timing] epoch: total_loss=27390.6860 total_time=0.3791s (avg batch 0.013s)
2026-09-09 12:21:28,311 INFO [epoch 03] train loss 0.8420 train acc 0.5422 | val loss 3.7744 val acc 0.0226
2026-09-09 12:21:29,410 INFO [timing] epoch: total_loss=11756.1285 total_time=1.0981s (avg batch 0.019s)
2026-09-09 12:21:29,791 INFO [timing] epoch: total_loss=31218.4815 total_time=0.3798s (avg batch 0.013s)
2026-09-09 12:21:29,792 INFO [epoch 04] train loss 0.8100 train acc 0.5556 | val loss 4.3018 val acc 0.0222
2026-09-09 12:21:30,889 INFO [timing] epoch: total_loss=11558.9285 total_time=1.0961s (avg batch 0.019s)
2026-09-09 12:21:31,270 INFO [timing] epoch: total_loss=32446.8519 total_time=0.3798s (avg batch 0.013s)
2026-09-09 12:21:31,271 INFO [epoch 05] train loss 0.7964 train acc 0.5473 | val loss 4.4711 val acc 0.0220
2026-09-09 12:21:32,358 INFO [timing] epoch: total_loss=11311.1892 total_time=1.0864s (avg batch 0.019s)
2026-09-09 12:21:32,734 INFO [timing] epoch: total_loss=35184.4109 total_time=0.3742s (avg batch 0.013s)
2026-09-09 12:21:32,735 INFO [epoch 06] train loss 0.7793 train acc 0.5697 | val loss 4.8483 val acc 0.0047
2026-09-09 12:21:33,891 INFO [timing] epoch: total_loss=11137.1419 total_time=1.1538s (avg batch 0.020s)
2026-09-09 12:21:34,276 INFO [timing] epoch: total_loss=35756.3370 total_time=0.3834s (avg batch 0.013s)
2026-09-09 12:21:34,278 INFO [epoch 07] train loss 0.7673 train acc 0.5547 | val loss 4.9272 val acc 0.0047
2026-09-09 12:21:35,386 INFO [timing] epoch: total_loss=11165.7404 total_time=1.1074s (avg batch 0.019s)
2026-09-09 12:21:35,767 INFO [timing] epoch: total_loss=37253.5880 total_time=0.3787s (avg batch 0.013s)
2026-09-09 12:21:35,768 INFO [epoch 08] train loss 0.7693 train acc 0.5597 | val loss 5.1335 val acc 0.0050
2026-09-09 12:21:36,921 INFO [timing] epoch: total_loss=11152.6672 total_time=1.1525s (avg batch 0.020s)
2026-09-09 12:21:37,342 INFO [timing] epoch: total_loss=37641.7163 total_time=0.4185s (avg batch 0.014s)
2026-09-09 12:21:37,343 INFO [epoch 09] train loss 0.7684 train acc 0.5625 | val loss 5.1870 val acc 0.0050
2026-09-09 12:21:38,515 INFO [timing] epoch: total_loss=10898.0640 total_time=1.1712s (avg batch 0.021s)
2026-09-09 12:21:38,928 INFO [timing] epoch: total_loss=39356.8072 total_time=0.4116s (avg batch 0.014s)
2026-09-09 12:21:38,930 INFO [epoch 10] train loss 0.7509 train acc 0.5648 | val loss 5.4233 val acc 0.0047
2026-09-09 12:21:40,126 INFO [timing] epoch: total_loss=11004.5765 total_time=1.1951s (avg batch 0.021s)
2026-09-09 12:21:40,539 INFO [timing] epoch: total_loss=40553.1541 total_time=0.4125s (avg batch 0.014s)
2026-09-09 12:21:40,540 INFO [epoch 11] train loss 0.7582 train acc 0.5630 | val loss 5.5881 val acc 0.0047
2026-09-09 12:21:41,703 INFO [timing] epoch: total_loss=10939.0029 total_time=1.1620s (avg batch 0.020s)
2026-09-09 12:21:42,088 INFO [timing] epoch: total_loss=42069.1414 total_time=0.3840s (avg batch 0.013s)

In [20]:
# run with best params
best_params_path = "artifacts/best_params.json"
if not os.path.exists(best_params_path):
    raise FileNotFoundError(best_params_path)
best = json.load(open(best_params_path, "r", encoding="utf-8"))
cfg = best.get("config", {})

# create a minimal template

template = SimpleNamespace(
    feature_store="feature_store",
    graphs_dir="graphs",
    split_train="train",
    split_val="val",
    hidden=128,
    layers=2,
    aggregator="mean",
    edge_in=0,
    edge_mlp_hidden=128,
    dropout=0.3,
    fanouts="25,15",
    batch_size=2048,
    epochs=25,
    lr=3e-4,
    weight_decay=1e-4,
    device="cuda" if torch.cuda.is_available() else "cpu",
    num_workers=0,
    seed=42,
    debug=False,
)

args = copy.deepcopy(template)
# override template with saved config values
for k, v in cfg.items():
    # ensure fanouts is a string as expected by run_training
    if k == "fanouts" and not isinstance(v, str):
        v = str(v)
    setattr(args, k, v)

# set epochs to 25
args.epochs = 25

print("Running training with:", {k: getattr(args, k) for k in ("hidden","aggregator","fanouts","dropout","epochs", "batch_size")})
res = run_training(args)

# save metrics
history = res.get("history", None)
os.makedirs("artifacts", exist_ok=True)

full_hist_path = "artifacts/best_history.json"
if history is not None:
    with open(full_hist_path, "w", encoding="utf-8") as f:
        json.dump(history, f, indent=2)
    print(f"Saved full-graph history -> {full_hist_path}")
else:
    print("Warning: run_training did not return 'history'; nothing to save.")

Running training with: {'hidden': 128, 'aggregator': 'mean', 'fanouts': '25,15', 'dropout': 0.2, 'epochs': 25, 'batch_size': 1024}
2026-09-09 12:34:47,627 INFO [model] SAGE[0]: in=None out=None hidden=128 edge_in=52 in_node=0
2026-09-09 12:34:53,690 INFO [timing] epoch: total_loss=120940.8291 total_time=6.0102s (avg batch 0.042s)
2026-09-09 12:34:55,134 INFO [timing] epoch: total_loss=87815.0219 total_time=1.4415s (avg batch 0.020s)
2026-09-09 12:34:55,134 INFO [epoch 01] train loss 0.8332 train acc 0.5897 | val loss 1.2101 val acc 0.6773
2026-09-09 12:35:00,827 INFO [timing] epoch: total_loss=78929.5948 total_time=5.6911s (avg batch 0.040s)
2026-09-09 12:35:02,230 INFO [timing] epoch: total_loss=98810.8632 total_time=1.4017s (avg batch 0.020s)
2026-09-09 12:35:02,230 INFO [epoch 02] train loss 0.5438 train acc 0.6479 | val loss 1.3616 val acc 0.6772
2026-09-09 12:35:07,917 INFO [timing] epoch: total_loss=67115.4056 total_time=5.6864s (avg batch 0.040s)
2026-09-09 12:35:09,338 INFO [timing] epoch: total_loss=122975.1386 total_time=1.4199s (avg batch 0.020s)
2026-09-09 12:35:09,340 INFO [epoch 03] train loss 0.4624 train acc 0.7127 | val loss 1.6945 val acc 0.6155
2026-09-09 12:35:15,021 INFO [timing] epoch: total_loss=60324.6537 total_time=5.6803s (avg batch 0.040s)
2026-09-09 12:35:16,435 INFO [timing] epoch: total_loss=144031.8644 total_time=1.4131s (avg batch 0.020s)
2026-09-09 12:35:16,438 INFO [epoch 04] train loss 0.4156 train acc 0.7561 | val loss 1.9847 val acc 0.6019
2026-09-09 12:35:22,083 INFO [timing] epoch: total_loss=55184.1998 total_time=5.6455s (avg batch 0.040s)
2026-09-09 12:35:23,495 INFO [timing] epoch: total_loss=139152.3564 total_time=1.4119s (avg batch 0.020s)
2026-09-09 12:35:23,496 INFO [epoch 05] train loss 0.3802 train acc 0.7775 | val loss 1.9175 val acc 0.6122
2026-09-09 12:35:29,224 INFO [timing] epoch: total_loss=51113.0460 total_time=5.7271s (avg batch 0.040s)
2026-09-09 12:35:30,632 INFO [timing] epoch: total_loss=166537.7983 total_time=1.4055s (avg batch 0.020s)
2026-09-09 12:35:30,634 INFO [epoch 06] train loss 0.3521 train acc 0.8015 | val loss 2.2948 val acc 0.6001
2026-09-09 12:35:36,394 INFO [timing] epoch: total_loss=48593.7992 total_time=5.7601s (avg batch 0.041s)
2026-09-09 12:35:37,876 INFO [timing] epoch: total_loss=186952.4932 total_time=1.4801s (avg batch 0.021s)
2026-09-09 12:35:37,879 INFO [epoch 07] train loss 0.3348 train acc 0.8205 | val loss 2.5761 val acc 0.5946
2026-09-09 12:35:43,572 INFO [timing] epoch: total_loss=46156.0513 total_time=5.6931s (avg batch 0.040s)
2026-09-09 12:35:44,978 INFO [timing] epoch: total_loss=199576.7072 total_time=1.4046s (avg batch 0.020s)
2026-09-09 12:35:44,978 INFO [epoch 08] train loss 0.3180 train acc 0.8357 | val loss 2.7501 val acc 0.5903
2026-09-09 12:35:50,715 INFO [timing] epoch: total_loss=44185.3171 total_time=5.7367s (avg batch 0.040s)
2026-09-09 12:35:52,127 INFO [timing] epoch: total_loss=208555.5406 total_time=1.4106s (avg batch 0.020s)
2026-09-09 12:35:52,127 INFO [epoch 09] train loss 0.3044 train acc 0.8564 | val loss 2.8738 val acc 0.5750
2026-09-09 12:35:57,974 INFO [timing] epoch: total_loss=41536.8872 total_time=5.8475s (avg batch 0.041s)
2026-09-09 12:35:59,431 INFO [timing] epoch: total_loss=233706.2353 total_time=1.4541s (avg batch 0.020s)
2026-09-09 12:35:59,431 INFO [epoch 10] train loss 0.2862 train acc 0.8713 | val loss 3.2204 val acc 0.5356
2026-09-09 12:36:05,137 INFO [timing] epoch: total_loss=40339.0821 total_time=5.7034s (avg batch 0.040s)
2026-09-09 12:36:06,550 INFO [timing] epoch: total_loss=228602.4986 total_time=1.4123s (avg batch 0.020s)
2026-09-09 12:36:06,553 INFO [epoch 11] train loss 0.2779 train acc 0.8820 | val loss 3.1501 val acc 0.6007
2026-09-09 12:36:12,211 INFO [timing] epoch: total_loss=39587.9265 total_time=5.6575s (avg batch 0.040s)
2026-09-09 12:36:13,617 INFO [timing] epoch: total_loss=251339.5261 total_time=1.4054s (avg batch 0.020s)
2026-09-09 12:36:13,618 INFO [epoch 12] train loss 0.2727 train acc 0.8907 | val loss 3.4634 val acc 0.5750
2026-09-09 12:36:19,291 INFO [timing] epoch: total_loss=38570.5933 total_time=5.6725s (avg batch 0.040s)
2026-09-09 12:36:20,703 INFO [timing] epoch: total_loss=275045.4432 total_time=1.4111s (avg batch 0.020s)
2026-09-09 12:36:20,705 INFO [epoch 13] train loss 0.2657 train acc 0.8969 | val loss 3.7900 val acc 0.4730
2026-09-09 12:36:26,416 INFO [timing] epoch: total_loss=37274.2373 total_time=5.7099s (avg batch 0.040s)
2026-09-09 12:36:27,850 INFO [timing] epoch: total_loss=271693.6854 total_time=1.4328s (avg batch 0.020s)
2026-09-09 12:36:27,851 INFO [epoch 14] train loss 0.2568 train acc 0.9021 | val loss 3.7438 val acc 0.5398
2026-09-09 12:36:33,618 INFO [timing] epoch: total_loss=36304.8614 total_time=5.7665s (avg batch 0.041s)
2026-09-09 12:36:35,071 INFO [timing] epoch: total_loss=278788.1968 total_time=1.4509s (avg batch 0.020s)
2026-09-09 12:36:35,071 INFO [epoch 15] train loss 0.2501 train acc 0.9047 | val loss 3.8416 val acc 0.5538
2026-09-09 12:36:41,417 INFO [timing] epoch: total_loss=36027.8448 total_time=6.3446s (avg batch 0.045s)
2026-09-09 12:36:42,917 INFO [timing] epoch: total_loss=271737.2972 total_time=1.4970s (avg batch 0.021s)
2026-09-09 12:36:42,917 INFO [epoch 16] train loss 0.2482 train acc 0.9086 | val loss 3.7444 val acc 0.6027
2026-09-09 12:36:48,903 INFO [timing] epoch: total_loss=35161.1921 total_time=5.9841s (avg batch 0.042s)
2026-09-09 12:36:50,372 INFO [timing] epoch: total_loss=295161.1801 total_time=1.4664s (avg batch 0.021s)
2026-09-09 12:36:50,374 INFO [epoch 17] train loss 0.2422 train acc 0.9099 | val loss 4.0672 val acc 0.5430
2026-09-09 12:36:56,312 INFO [timing] epoch: total_loss=34408.8988 total_time=5.9383s (avg batch 0.042s)
2026-09-09 12:36:57,783 INFO [timing] epoch: total_loss=265744.1499 total_time=1.4673s (avg batch 0.021s)
2026-09-09 12:36:57,783 INFO [epoch 18] train loss 0.2371 train acc 0.9143 | val loss 3.6619 val acc 0.5831
2026-09-09 12:37:03,866 INFO [timing] epoch: total_loss=34402.8276 total_time=6.0811s (avg batch 0.043s)
2026-09-09 12:37:05,442 INFO [timing] epoch: total_loss=313803.2767 total_time=1.5749s (avg batch 0.022s)
2026-09-09 12:37:05,444 INFO [epoch 19] train loss 0.2370 train acc 0.9133 | val loss 4.3241 val acc 0.5474
2026-09-09 12:37:11,444 INFO [timing] epoch: total_loss=33437.0197 total_time=5.9987s (avg batch 0.042s)
2026-09-09 12:37:12,916 INFO [timing] epoch: total_loss=303411.4157 total_time=1.4712s (avg batch 0.021s)
2026-09-09 12:37:12,918 INFO [epoch 20] train loss 0.2304 train acc 0.9151 | val loss 4.1809 val acc 0.5514
2026-09-09 12:37:18,837 INFO [timing] epoch: total_loss=33454.5885 total_time=5.9186s (avg batch 0.042s)
2026-09-09 12:37:20,311 INFO [timing] epoch: total_loss=319875.9351 total_time=1.4720s (avg batch 0.021s)
2026-09-09 12:37:20,313 INFO [epoch 21] train loss 0.2305 train acc 0.9165 | val loss 4.4078 val acc 0.5448
2026-09-09 12:37:26,293 INFO [timing] epoch: total_loss=33942.4386 total_time=5.9789s (avg batch 0.042s)
2026-09-09 12:37:27,762 INFO [timing] epoch: total_loss=316298.0830 total_time=1.4678s (avg batch 0.021s)
2026-09-09 12:37:27,765 INFO [epoch 22] train loss 0.2338 train acc 0.9184 | val loss 4.3585 val acc 0.5471
2026-09-09 12:37:33,723 INFO [timing] epoch: total_loss=32658.1666 total_time=5.9581s (avg batch 0.042s)
2026-09-09 12:37:35,211 INFO [timing] epoch: total_loss=335517.1243 total_time=1.4859s (avg batch 0.021s)
2026-09-09 12:37:35,213 INFO [epoch 23] train loss 0.2250 train acc 0.9189 | val loss 4.6233 val acc 0.5577
2026-09-09 12:37:41,246 INFO [timing] epoch: total_loss=32476.1347 total_time=6.0326s (avg batch 0.042s)
2026-09-09 12:37:42,730 INFO [timing] epoch: total_loss=313831.4665 total_time=1.4818s (avg batch 0.021s)
2026-09-09 12:37:42,732 INFO [epoch 24] train loss 0.2237 train acc 0.9210 | val loss 4.3245 val acc 0.5668
2026-09-09 12:37:48,716 INFO [timing] epoch: total_loss=32457.9113 total_time=5.9838s (avg batch 0.042s)
2026-09-09 12:37:50,201 INFO [timing] epoch: total_loss=327583.7480 total_time=1.4829s (avg batch 0.021s)
2026-09-09 12:37:50,201 INFO [epoch 25] train loss 0.2236 train acc 0.9197 | val loss 4.5140 val acc 0.5591
2026-09-09 12:37:50,201 INFO Best val acc: 0.6773
Saved full-graph history -> artifacts/best_history.json

In [21]:
print("Train:")
print(df_train["label"].value_counts())
print("\nVal:")
print(df_val["label"].value_counts())
print("\nTest:")
print(df_test["label"].value_counts())

Train:
label
DoS               114776
Reconnaissance     24220
DDoS                5444
Benign               709
Name: count, dtype: int64

Val:
label
DDoS      72556
Benign       15
Name: count, dtype: int64

Test:
label
DDoS      24153
Theft        26
Benign       12
Name: count, dtype: int64